"""Export the model (parts.py) to the EXO game: src/heroes/vanguard-ref-data.js = boxes per rig joint in hanging joint-local voxel units
(1 voxel = 0.0273 pose units), plus the spear.  Tabard parts are not exported as boxes: the game builds them as spring chains.

usage: /usr/bin/python3 export_game.py [game_repo_root]
"""
import json, sys
from pathlib import Path
import model as M

GAME = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Projects/boxin game?/vg-game"
JOINT_MAP = {"shoulderL": "pauldronL", "shoulderR": "pauldronR"}
boxes = {}
spear = []
for j, bl in M.game_boxes().items():
    if j == "spear":
        spear = [list(b[:6]) + [b[6]] for b in bl]; continue
    bl = [b for b in bl]
    out = []
    for (x0, y0, z0, x1, y1, z1, c) in bl:
        out.append([x0, y0, z0, x1, y1, z1, c])
    boxes[JOINT_MAP.get(j, j)] = out
# tabards are chains in game
tab = {"hips": [b for b in boxes["hips"]]}
ids = {}
for p in M.expanded():
    if p["id"].startswith("tabard"):
        ids[tuple(p["box"])] = p["id"]
boxes["hips"] = [b for b in boxes["hips"] if tuple(b[:6]) not in ids]
js = "// GENERATED by img2-builds/vanguard2/export_game.py from parts.py (Vanguard turnaround, vanguard_ref.png) — do not edit.\n"
js += "// Boxes [x0,y0,z0,x1,y1,z1,colour] per rig joint, hanging joint-local voxel units; colour I ivory N navy O orange K black D dark B blade.\n"
js += f"export const VOXEL = 0.0273;\nexport const BOXES = {json.dumps(boxes, separators=(',', ':'))};\nexport const SPEAR = {json.dumps(spear, separators=(',', ':'))};\n"
out = GAME / "src/heroes/vanguard-ref-data.js"
out.write_text(js)
print(out, len(js), {k: len(v) for k, v in boxes.items()}, "spear", len(spear))
