"""Export the voxel Vanguard to the game's hero format: per-rig-joint voxel grids (run-length coded) + rig dimensions.
Writes  <game>/src/heroes/vanguard-data.js .  Joint pivots are our sheet-space voxel coordinates; parts are stored relative
to their game joint so the game's rig (rest pose = limbs hanging, chain axes vertical) reproduces the model exactly.
"""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import vanguard_parts as VP

GAME = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Projects/boxin game?/vg-game"
V = 0.0245
rows = json.load(open(Path(__file__).parent / "vox/vanguard_voxels.json"))

PIV = {"hips": (0, 38, 0), "spine": (0, 40, 0), "chest": (0, 44, 0), "neck": (0, 58, 0), "head": (0, 60, 0)}
for s, sg in (("L", 1), ("R", -1)):
    PIV.update({f"pauldron{s}": (sg * 17, 55, 0), f"upperArm{s}": (sg * 17, 55, 0), f"foreArm{s}": (sg * 17, 46, 0), f"hand{s}": (sg * 17, 32, 0),
                f"thigh{s}": (sg * 12, 37, 0), f"shin{s}": (sg * 12, 22, 0), f"foot{s}": (sg * 12, 3, 0)})
WAIST_PARTS = {"hips_core", "waist_plate", "waist_light", "hip_cube_L", "hip_cube_R"}


def game_joint(x, y, z, c, j, part):
    if j == "hips":
        return "spine" if (part in WAIST_PARTS and y >= 41) else "hips"
    if j == "chest":
        return "chest"
    if j == "head":
        return "neck" if part == "neck" else "head"
    side = j[-1] if j[-1] in "LR" else ""
    base = j[:-1] if side else j
    if base == "shoulder":
        return ("pauldron" if part.startswith("pauldron") else "upperArm") + side
    return {"elbow": "foreArm", "wrist": "hand", "thigh": "thigh", "shin": "shin", "foot": "foot"}[base] + side


# ---- proportion pass: stretch legs / torso / forearm by duplicating plain rows inside each rig group (keeps voxels cubic).
# new_y = y + base + #(cuts <= y); a cut row is emitted twice.  Pivots are remapped the same way.
STRETCH = {   # group prefix: (base shift, cut rows in sheet y)
    "foot": (0, []), "shin": (0, [13, 17]), "thigh": (2, [29, 33]),
    "hips": (2, [30, 34]), "spine": (4, []), "chest": (4, [50, 54]), "neck": (6, []), "head": (6, []),
    "pauldron": (6, []), "upperArm": (6, []), "foreArm": (5, [40]), "hand": (5, []),
}
def _stretch(g):
    return STRETCH[g[:-1] if g[-1] in "LR" else g]
def warp_y(g, y):
    b, cuts = _stretch(g)
    return y + b + sum(1 for c in cuts if c <= y)

CODE = {"I": 1, "N": 2, "O": 3, "G": 4, "K": 5, "D": 6, "S": 7}
groups = {}
for x, y, z, c, j, part in rows:
    g = game_joint(x, y, z, c, j, part)
    px, py, pz = PIV[g]
    ny = warp_y(g, y); npy = warp_y(g, py)
    groups.setdefault(g, []).append((x - px, ny - npy, z - pz, CODE[c]))
    if y in _stretch(g)[1]:
        groups[g].append((x - px, ny - 1 - npy, z - pz, CODE[c]))


def encode(cells):
    xs, ys, zs = zip(*[(a, b, c) for a, b, c, _ in cells])
    o = (min(xs), min(ys), min(zs)); n = (max(xs) - o[0] + 1, max(ys) - o[1] + 1, max(zs) - o[2] + 1)
    grid = bytearray(n[0] * n[1] * n[2])
    for a, b, c, v in cells:
        grid[(a - o[0]) + n[0] * ((b - o[1]) + n[1] * (c - o[2]))] = v
    rle = []; run = 1
    for i in range(1, len(grid) + 1):
        if i < len(grid) and grid[i] == grid[i - 1]:
            run += 1
        else:
            rle += [grid[i - 1], run]; run = 1
    return dict(o=list(o), n=list(n), rle=rle)


data = {g: encode(cells) for g, cells in groups.items()}

# ---- spear: rasterise its boxes (authored vertical around x=z=0), re-express with the shaft along +Z from the grip
GRIP_Y = 12
sp = []
for pt in VP.all_parts():
    if pt["joint"] != "spear":
        continue
    x0, y0, z0, x1, y1, z1 = pt["box"]
    import math
    for x in range(math.floor(x0), math.ceil(x1)):
        for y in range(math.floor(y0), math.ceil(y1)):
            for z in range(math.floor(z0), math.ceil(z1)):
                sp.append((x, z, y - GRIP_Y, CODE[pt["color"]]))
dedup = {}
for a, b, c, v in sp:
    dedup[(a, b, c)] = v                    # later (smaller) boxes win
spear = encode([(a, b, c, v) for (a, b, c), v in dedup.items()])
spear_tip = max(c for (_, _, c) in dedup)
spear_head = min(c for (a, b, c), v in dedup.items() if v in (2, 3) and c > 40)
dim = dict(thigh=17 * V, shin=21 * V, upper=9 * V, fore=15 * V, spine=0.0, hipX=12 * V, hipY=-1 * V, shoulderX=17 * V, shoulderY=13 * V, shoulderZ=0.0,
           spineUp=2 * V, chestUp=4 * V, neck=16 * V, hipLift=0.06, headUp=2 * V, footDX=12 * V - 0.11, spearTip=(spear_tip + 1) * V, spearHead=spear_head * V)
js = "// GENERATED by tools/vanguard (img2-builds/vanguard/export_game.py) — voxel Vanguard reconstructed from the sheet views.\n"
js += f"export const VOXEL = {V};\nexport const RIG_DIM = {json.dumps({k: round(v, 5) for k, v in dim.items()})};\n"
js += f"export const PIVOTS = {json.dumps(PIV)};\nexport const GROUPS = {json.dumps(data, separators=(',', ':'))};\nexport const SPEAR = {json.dumps(spear, separators=(',', ':'))};\n"
out = GAME / "src/heroes/vanguard-data.js"
out.write_text(js)
print(out, len(js), {g: len(c) for g, c in groups.items()}, "spear cells", len(dedup), "tip", spear_tip, "head", spear_head)
